services:
  duckhunt:
    build: .
    container_name: duckhunt
    image: duckhunt
    volumes:
      - ./db:/app/db
    environment:
      - TOKEN=${TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - GUILD_ID=${GUILD_ID}
